name: arduino_mobile_ide
description: Arduino mobile IDE for Android and web, inspired by ArduinoDroid, Wokwi, and Proto.io.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.0.0
  material_design_icons_flutter: ^7.0.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
